# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import campaign_pb2 as campaign__pb2


class CampaignServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCampaign = channel.unary_unary(
                '/campaign.CampaignService/GetCampaign',
                request_serializer=campaign__pb2.GetCampaignRequest.SerializeToString,
                response_deserializer=campaign__pb2.GetCampaignResponse.FromString,
                )
        self.CheckCampaignActive = channel.unary_unary(
                '/campaign.CampaignService/CheckCampaignActive',
                request_serializer=campaign__pb2.CheckCampaignActiveRequest.SerializeToString,
                response_deserializer=campaign__pb2.CheckCampaignActiveResponse.FromString,
                )


class CampaignServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCampaign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCampaignActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CampaignServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCampaign': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCampaign,
                    request_deserializer=campaign__pb2.GetCampaignRequest.FromString,
                    response_serializer=campaign__pb2.GetCampaignResponse.SerializeToString,
            ),
            'CheckCampaignActive': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCampaignActive,
                    request_deserializer=campaign__pb2.CheckCampaignActiveRequest.FromString,
                    response_serializer=campaign__pb2.CheckCampaignActiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campaign.CampaignService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CampaignService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCampaign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/campaign.CampaignService/GetCampaign',
            campaign__pb2.GetCampaignRequest.SerializeToString,
            campaign__pb2.GetCampaignResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCampaignActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/campaign.CampaignService/CheckCampaignActive',
            campaign__pb2.CheckCampaignActiveRequest.SerializeToString,
            campaign__pb2.CheckCampaignActiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
