# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product/product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15product/product.proto\x12\x07product\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"L\n\x12GetProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\r\n\x05stock\x18\x04 \x01(\x05\"@\n\x18\x43heckAvailabilityRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"=\n\x19\x43heckAvailabilityResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\r\n\x05stock\x18\x02 \x01(\x05\x32\xb3\x01\n\x0eProductService\x12\x45\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x1b.product.GetProductResponse\x12Z\n\x11\x43heckAvailability\x12!.product.CheckAvailabilityRequest\x1a\".product.CheckAvailabilityResponseB\x1bZ\x19product-svc/proto;productb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product.product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\031product-svc/proto;product'
  _GETPRODUCTREQUEST._serialized_start=34
  _GETPRODUCTREQUEST._serialized_end=73
  _GETPRODUCTRESPONSE._serialized_start=75
  _GETPRODUCTRESPONSE._serialized_end=151
  _CHECKAVAILABILITYREQUEST._serialized_start=153
  _CHECKAVAILABILITYREQUEST._serialized_end=217
  _CHECKAVAILABILITYRESPONSE._serialized_start=219
  _CHECKAVAILABILITYRESPONSE._serialized_end=280
  _PRODUCTSERVICE._serialized_start=283
  _PRODUCTSERVICE._serialized_end=462
# @@protoc_insertion_point(module_scope)
