# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: campaign.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61mpaign.proto\x12\x08\x63\x61mpaign\")\n\x12GetCampaignRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\x05\"\xc9\x01\n\x13GetCampaignResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\x11\n\tis_active\x18\x08 \x01(\x08\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x12\n\nupdated_at\x18\n \x01(\t\"1\n\x1a\x43heckCampaignActiveRequest\x12\x13\n\x0b\x63\x61mpaign_id\x18\x01 \x01(\x05\"S\n\x1b\x43heckCampaignActiveResponse\x12\x11\n\tis_active\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t2\xc1\x01\n\x0f\x43\x61mpaignService\x12J\n\x0bGetCampaign\x12\x1c.campaign.GetCampaignRequest\x1a\x1d.campaign.GetCampaignResponse\x12\x62\n\x13\x43heckCampaignActive\x12$.campaign.CheckCampaignActiveRequest\x1a%.campaign.CheckCampaignActiveResponseB\x1dZ\x1b\x63\x61mpaign-svc/proto;campaignb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'campaign_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\033campaign-svc/proto;campaign'
  _GETCAMPAIGNREQUEST._serialized_start=28
  _GETCAMPAIGNREQUEST._serialized_end=69
  _GETCAMPAIGNRESPONSE._serialized_start=72
  _GETCAMPAIGNRESPONSE._serialized_end=273
  _CHECKCAMPAIGNACTIVEREQUEST._serialized_start=275
  _CHECKCAMPAIGNACTIVEREQUEST._serialized_end=324
  _CHECKCAMPAIGNACTIVERESPONSE._serialized_start=326
  _CHECKCAMPAIGNACTIVERESPONSE._serialized_end=409
  _CAMPAIGNSERVICE._serialized_start=412
  _CAMPAIGNSERVICE._serialized_end=605
# @@protoc_insertion_point(module_scope)
